# Generated by Django 5.2.6 on 2025-09-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='history',
            field=models.JSONField(default=list),
        ),
    ]
