# Generated by Django 5.2.6 on 2025-09-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('Legal', 'Legal'), ('Contracts', 'Contracts'), ('Tech', 'Technical Reports'), ('Invoices', 'Invoices')], max_length=50, null=True),
        ),
    ]
