# Generated by Django 5.2.6 on 2025-09-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('Finance', 'Finance'), ('HR', 'HR'), ('Legal', 'Legal'), ('Contracts', 'Contracts'), ('Tech', 'Technical Reports'), ('Invoices', 'Invoices'), ('Unknown', 'Unknown')], default='Unknown', max_length=50, null=True),
        ),
    ]
