# Generated by Django 5.2.6 on 2025-09-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
