# Generated by Django 5.2.6 on 2025-09-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_accesslog_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'TXT'), ('csv', 'CSV'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
